-- ============================================================
-- PEKUNCEN DIGITAL — RW 08, Blok Pekuncen (RT 29, 30, 31, 32)
-- Schema database Supabase (PostgreSQL)
-- ============================================================
-- CATATAN PENTING SEBELUM MENJALANKAN:
-- 1. Jalankan file ini di Supabase project BARU (jangan project lama).
-- 2. Setelah dijalankan, admin default: username "adminrw", password "admin123"
--    (password sudah di-hash otomatis oleh script ini, TIDAK disimpan plain text).
--    -> SEGERA ganti password ini setelah login pertama kali!
-- 3. rt VALID VALUES: '29', '30', '31', '32'. rt = NULL artinya data
--    berlaku di tingkat RW (bukan milik salah satu RT saja) — dipakai
--    untuk kas/aset bersama RW jika suatu saat dibutuhkan.
-- ============================================================

-- Ekstensi untuk hashing password (bcrypt)
-- Supabase secara default memasang extension di schema "extensions" (bukan
-- "public"), makanya di bawah kita eksplisit arahkan ke sana.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ============================================================
-- 1. Tabel Users (Akun Login Pengguna & Admin)
-- ============================================================
CREATE TABLE IF NOT EXISTS "Users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT UNIQUE,
    "password" TEXT, -- disimpan sebagai bcrypt hash, JANGAN pernah isi plain text manual
    "role" TEXT,      -- 'RT' = Admin RW (nama kolom dipertahankan agar kompatibel dgn kode), 'Warga' = warga
    "nama" TEXT,
    "nik" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32')) -- NULL untuk admin RW; diisi utk akun warga
);

-- 2. Tabel Sessions (Token Sesi Login Aktif)
CREATE TABLE IF NOT EXISTS "Sessions" (
    "token" TEXT PRIMARY KEY,
    "nik" TEXT,
    "role" TEXT,
    "createdat" TEXT
);

-- 3. Tabel Warga (Data Kependudukan) — kini bertag per-RT
CREATE TABLE IF NOT EXISTS "Warga" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_lengkap" TEXT,
    "nama_panggilan" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "tempat_lahir" TEXT,
    "tanggal_lahir" TEXT,
    "jenis_kelamin" TEXT,
    "alamat" TEXT,
    "status_nikah" TEXT,
    "status_tinggal" TEXT,
    "pekerjaan" TEXT,
    "no_hp" TEXT,
    "foto_url" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 4. Tabel Iuran (Tagihan & Pembayaran Iuran Warga)
CREATE TABLE IF NOT EXISTS "Iuran" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nik" TEXT,
    "nama" TEXT,
    "no_kk" TEXT,
    "bulan" TEXT,
    "tahun" NUMERIC,
    "nominal" NUMERIC,
    "status" TEXT,
    "tanggal_bayar" TEXT,
    "diterima_oleh" TEXT,
    "bukti_transfer" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 5. Tabel Pengaduan (Laporan Aduan Warga)
CREATE TABLE IF NOT EXISTS "Pengaduan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_hp" TEXT,
    "jenis_aduan" TEXT,
    "keterangan" TEXT,
    "tanggal" TEXT,
    "foto_url" TEXT,
    "status" TEXT,
    "foto_penyelesaian" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 6. Tabel SuratPengantar (Pengajuan Surat Warga)
CREATE TABLE IF NOT EXISTS "SuratPengantar" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "alamat" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32')),
    "rw" TEXT DEFAULT '08',
    "jenis_surat" TEXT,
    "status" TEXT,
    "keterangan_admin" TEXT
);

-- 7. Tabel Keuangan (Kas Pemasukan & Pengeluaran) — per RT, atau RW jika rt NULL
CREATE TABLE IF NOT EXISTS "Keuangan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tanggal" TEXT,
    "pemasukan" NUMERIC,
    "pengeluaran" NUMERIC,
    "keterangan" TEXT,
    "saldo" NUMERIC,
    "foto_url" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 8. Tabel Sumbangan (Sumbangan Warga)
CREATE TABLE IF NOT EXISTS "Sumbangan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "tanggal" TEXT,
    "jenis_sumbangan" TEXT,
    "keterangan" TEXT,
    "nominal" NUMERIC,
    "bukti_transfer" TEXT,
    "status" TEXT,
    "nik" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 9. Tabel Aset (Inventaris Barang) — per RT, atau RW jika rt NULL
CREATE TABLE IF NOT EXISTS "Aset" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_barang" TEXT,
    "kondisi" TEXT,
    "jumlah" NUMERIC,
    "status_barang" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 10. Tabel Peminjaman (Pinjam Barang)
CREATE TABLE IF NOT EXISTS "Peminjaman" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_peminjam" TEXT,
    "id_barang" TEXT,
    "nama_barang" TEXT,
    "jumlah_minta" NUMERIC,
    "acc" NUMERIC,
    "keterangan" TEXT,
    "catatan_rt" TEXT,
    "status" TEXT,
    "tanggal" TEXT,
    "nik" TEXT,
    "jumlah" NUMERIC,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 11. Tabel Aspirasi (Kotak Saran & Masukan Warga)
CREATE TABLE IF NOT EXISTS "Aspirasi" (
    "id" TEXT PRIMARY KEY,
    "tanggal" TEXT,
    "isi_aspirasi" TEXT,
    "status" TEXT,
    "nama" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 12. Tabel Kelahiran (Data Kelahiran Warga)
CREATE TABLE IF NOT EXISTS "Kelahiran" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama_bayi" TEXT,
    "tanggal_lahir" TEXT,
    "nama_ayah" TEXT,
    "nama_ibu" TEXT,
    "alamat" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32'))
);

-- 13. Tabel Kematian (Data Kematian Warga)
CREATE TABLE IF NOT EXISTS "Kematian" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "tanggal_meninggal" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32')),
    "alamat" TEXT,
    "keterangan" TEXT
);

-- 14. Tabel PindahMasuk (Data Pindah Masuk Warga)
CREATE TABLE IF NOT EXISTS "PindahMasuk" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "asal" TEXT,
    "alamat_baru" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32')),
    "tanggal_pindah" TEXT,
    "status_pindah" TEXT
);

-- 15. Tabel PindahKeluar (Data Pindah Keluar Warga)
CREATE TABLE IF NOT EXISTS "PindahKeluar" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nama" TEXT,
    "nik" TEXT,
    "no_kk" TEXT,
    "alamat_tujuan" TEXT,
    "rt" TEXT CHECK ("rt" IN ('29','30','31','32')),
    "rw" TEXT DEFAULT '08',
    "tanggal_pindah" TEXT
);

-- 16. Tabel Pengaturan (Konfigurasi Aplikasi & Info RW) — tetap 1 baris global (RW-level)
CREATE TABLE IF NOT EXISTS "Pengaturan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kunci" TEXT UNIQUE,
    "nilai" TEXT
);

-- ============================================================
-- AKUN ADMIN DEFAULT (password di-hash, BUKAN plain text)
-- Username: adminrw | Password: admin123  -> GANTI SEGERA setelah login pertama
-- ============================================================
INSERT INTO "Users" ("username", "password", "role", "nama", "nik")
SELECT 'adminrw', extensions.crypt('admin123', extensions.gen_salt('bf')), 'RT', 'Administrator RW 08', '0'
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "username" = 'adminrw');

-- ============================================================
-- RPC 1: verify_user_login
-- Verifikasi login di sisi server (password TIDAK PERNAH dikirim balik
-- ke client, dan tabel Users tidak perlu di-select mentah dari browser
-- lagi hanya untuk proses login).
-- ============================================================
CREATE OR REPLACE FUNCTION verify_user_login(p_username TEXT, p_password TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user RECORD;
  v_warga RECORD;
BEGIN
  SELECT * INTO v_user FROM "Users"
    WHERE lower(trim(username)) = lower(trim(p_username))
    LIMIT 1;

  IF v_user IS NULL THEN
    RETURN json_build_object('status','error','message','Username atau Password salah!');
  END IF;

  IF v_user.password IS NULL OR v_user.password = '' THEN
    RETURN json_build_object('status','error','message','Akun ini belum memiliki password. Hubungi Admin RW.');
  END IF;

  IF extensions.crypt(p_password, v_user.password) <> v_user.password THEN
    RETURN json_build_object('status','error','message','Username atau Password salah!');
  END IF;

  SELECT * INTO v_warga FROM "Warga"
    WHERE nik = v_user.nik
       OR lower(trim(coalesce(nik,''))) = lower(trim(p_username))
    LIMIT 1;

  RETURN json_build_object(
    'status','success',
    'message','Login Berhasil!',
    'role', coalesce(v_user.role,'Warga'),
    'nik', coalesce(v_user.nik, p_username),
    'nama', coalesce(v_warga.nama_lengkap, v_user.nama, p_username),
    'alamat', coalesce(v_warga.alamat, ''),
    'noHp', coalesce(v_warga.no_hp, ''),
    'rt', coalesce(v_user.rt, v_warga.rt),
    'username', v_user.username
  );
END;
$$;

GRANT EXECUTE ON FUNCTION verify_user_login(TEXT, TEXT) TO anon;

-- ============================================================
-- RPC 2: admin_set_password
-- Satu-satunya cara password ditulis/diubah — selalu di-hash di server.
-- Dipakai untuk: buat akun baru, reset password, edit akun.
-- ============================================================
CREATE OR REPLACE FUNCTION admin_set_password(p_username TEXT, p_new_password TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  IF p_new_password IS NULL OR length(p_new_password) < 6 THEN
    RETURN json_build_object('status','error','message','Password minimal 6 karakter.');
  END IF;

  UPDATE "Users"
    SET password = extensions.crypt(p_new_password, extensions.gen_salt('bf'))
    WHERE lower(trim(username)) = lower(trim(p_username));

  IF NOT FOUND THEN
    RETURN json_build_object('status','error','message','Username tidak ditemukan.');
  END IF;

  RETURN json_build_object('status','success','message','Password berhasil diperbarui.');
END;
$$;

GRANT EXECUTE ON FUNCTION admin_set_password(TEXT, TEXT) TO anon;

-- ============================================================
-- RPC 3: get_warga_secured
-- Data warga: admin (role RT) lihat semua kolom penuh.
-- Warga biasa: NIK & No HP warga LAIN disamarkan, hanya data
-- miliknya sendiri (berdasar token sesi) yang tampil penuh.
-- ============================================================
CREATE OR REPLACE FUNCTION get_warga_secured(p_token TEXT DEFAULT NULL)
RETURNS SETOF "Warga"
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role TEXT := '';
  v_nik TEXT := '';
BEGIN
  IF p_token IS NOT NULL AND p_token <> '' THEN
    SELECT role, nik INTO v_role, v_nik FROM "Sessions" WHERE token = p_token LIMIT 1;
  END IF;

  IF lower(coalesce(v_role,'')) = 'rt' THEN
    RETURN QUERY SELECT * FROM "Warga";
  ELSE
    RETURN QUERY
      SELECT
        w.id, w.nama_lengkap, w.nama_panggilan,
        CASE WHEN w.nik = v_nik THEN w.nik
             ELSE left(coalesce(w.nik,''), 4) || repeat('*', greatest(length(coalesce(w.nik,''))-4, 0)) END,
        w.no_kk, w.tempat_lahir, w.tanggal_lahir, w.jenis_kelamin, w.alamat,
        w.status_nikah, w.status_tinggal, w.pekerjaan,
        CASE WHEN w.nik = v_nik THEN w.no_hp
             ELSE left(coalesce(w.no_hp,''), 4) || repeat('*', greatest(length(coalesce(w.no_hp,''))-4, 0)) END,
        w.foto_url, w.rt
      FROM "Warga" w;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION get_warga_secured(TEXT) TO anon;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
-- CATATAN JUJUR SOAL BATASAN ARSITEKTUR:
-- Aplikasi ini adalah situs statis (tanpa server sendiri) yang mengakses
-- Supabase langsung pakai satu "anon key" yang sama untuk semua pengunjung
-- (bukan Supabase Auth per-user). Karena itu, RLS di bawah ini TIDAK BISA
-- benar-benar membedakan "ini admin" vs "ini warga" di level database —
-- pembedaan itu hanya terjadi di kode aplikasi (JS), yang notabene bisa
-- dilihat/diubah orang yang cukup paham teknis lewat DevTools browser.
-- Untuk akses kontrol yang benar-benar aman di level database, upgrade
-- berikutnya yang disarankan: pindah ke Supabase Auth (login email/password
-- resmi) + RLS berbasis auth.uid(). Untuk skala RW dengan 4 RT dan risiko
-- yang wajar, perbaikan di bawah ini (password ter-hash + RPC login/ganti
-- password yang benar-benar berfungsi) sudah jauh lebih baik dibanding
-- kondisi sebelumnya (password plain text + RPC keamanan yang belum pernah
-- dibuat di database sehingga selalu jatuh ke mode tanpa proteksi).
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS "Public Access Policy" ON public.%I;', t);
        EXECUTE format('CREATE POLICY "Public Access Policy" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t);
    END LOOP;
END $$;

-- ============================================================
-- SELESAI — 16 tabel (semua bertag RT 29/30/31/32 kecuali Pengaturan),
-- 3 RPC keamanan (verify_user_login, admin_set_password, get_warga_secured)
-- ============================================================
